HW4 Testing
vm137/movies-db pull request #3
Opened 2019-03-26 18:25 UTC by vm137

2019-04-05 15:43 UTC, loginov-rocks requested changes
Please add `coverage` dir to `.gitignore` and remove them from this pull request.

2019-04-05 15:46 UTC, loginov-rocks commented on package.json
> +    "react-test-renderer": "^16.8.6",
`react-test-renderer` is not used, so it should be deleted from the dependencies list.

2019-04-05 15:47 UTC, loginov-rocks commented on package.json
> +    "sinon": "^7.3.1",
`sinon` is not used, so it should be deleted from the dependencies list.

2019-04-05 15:53 UTC, loginov-rocks commented on package.json
> +    "test": "jest src --env=jsdom",
Jsdom env is used by Jest by default, so the arg is not neccessary

2019-04-05 15:54 UTC, loginov-rocks commented on package.json
> +    "ci": "npm run lint && npm run build",
As we implemented tests we need to include them to our CI process, so please add the `npm run test` to the `ci` script.

2019-04-05 15:56 UTC, loginov-rocks commented
I don't see Cypress tests for the app, only default tests that we don't need to include.

2019-04-06 07:25 UTC, vm137 commented
I've made all requested changes and added cypress test.

2019-04-09 14:02 UTC, loginov-rocks commented on src/client/components/App.test.jsx
> +    const wrapper = render(<App />);
Please replace `render` to `shallow`

2019-04-09 14:02 UTC, loginov-rocks commented on src/client/components/App.test.jsx
> +describe('MovieCard', () => {
Please rename test to `App`

2019-04-09 14:25 UTC, loginov-rocks commented on src/client/components/MovieCard/MovieCard.test.jsx
> +describe('MovieCard', () => {
Please test handleClick method.

2019-04-09 14:30 UTC, loginov-rocks commented on src/client/components/SearchBlock/SearchBlock.test.jsx
> +describe('SearchBlock', () => {
Please test state changes after `updateInputValue` triggering by user input.

2019-04-09 14:31 UTC, loginov-rocks commented on src/client/components/SearchResults/SearchResults.test.jsx
> +const movies = [
Please extract this to a separate file like `./__fixtures__/movies.json`

2019-04-09 19:29 UTC, loginov-rocks requested changes
It seems `shallow()` doesn't return snapshot to compare, we have to add any serializer, I suggest https://www.npmjs.com/package/enzyme-to-json - please install it as dev dependency and add the following to package.json -> jest prop:
```
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
```
After that you can update snapshots and they will content JSON tree instead of `ShallowWrapper {}`

2019-04-09 19:29 UTC, loginov-rocks commented on src/client/components/ErrorBoundary/ErrorBoundary.test.jsx
> +    wrapper.find(ChildComponent).simulateError(error);
Nice job!

2019-04-09 19:29 UTC, loginov-rocks commented on src/client/components/SearchBlock/SearchBlock.test.jsx
> +    const wrapper = render(<SearchBlock
Still using `render`

2019-04-09 19:29 UTC, loginov-rocks commented on src/client/components/SearchResults/SearchResults.test.jsx
> +    const wrapper = render(<SearchResults
Still using `render`

2019-04-09 19:29 UTC, loginov-rocks commented on src/client/components/SingleMovie/SingleMovie.test.jsx
> +    const wrapper = render(<SingleMovie
Still using `render`

2019-04-09 20:26 UTC, vm137 commented on src/client/components/ErrorBoundary/ErrorBoundary.test.jsx
> +    wrapper.find(ChildComponent).simulateError(error);
cool! thank you.

2019-04-09 21:15 UTC, vm137 commented on src/client/components/SearchBlock/SearchBlock.test.jsx
> +    const wrapper = render(<SearchBlock
changed for mount()

2019-04-09 21:15 UTC, vm137 commented on src/client/components/SingleMovie/SingleMovie.test.jsx
> +    const wrapper = render(<SingleMovie
changed for shallow()

2019-04-09 21:17 UTC, loginov-rocks approved these changes
Congratulations!

2019-04-09 21:21 UTC, merged