hw7: SSR
vm137/movies-db pull request #7
Opened 2019-05-06 19:44 UTC by vm137

2019-05-13 16:04 UTC, loginov-rocks requested changes
Unfortunately, apart of the small bugs, I haven't found Redux state computing on the server.

For the images you can specify public path options for file-loader: https://github.com/webpack-contrib/file-loader#publicpath

2019-05-13 16:04 UTC, loginov-rocks commented on package.json
>      "lint": "eslint --ext js,jsx src",
Add new directories with JS files to the lint script: server, webpack

2019-05-13 16:04 UTC, loginov-rocks commented on package.json
> +    "ci": "npm run lint && npm test",
What was the reason to remove `npm run build` from the `ci` command? Please put it back, but after the `npm test` command.

2019-05-13 16:04 UTC, loginov-rocks commented on server/app.js
> +  const serverRenderer = require('../public/js/serverRenderer').default;
You can `// eslint-disable-line` this line, because errors are expected.

2019-05-13 16:04 UTC, loginov-rocks commented on package.json
> +    "ssr": "cross-env NODE_ENV=development  node src/server/index.js"
This is a wrong command, prefer `start` for that operation.

2019-05-13 16:04 UTC, loginov-rocks commented on package.json
>      "build": "webpack --mode=production",
This command doesn't work, you have to specify path to the config file using `--config` arg. And also please check that it works

2019-05-13 16:04 UTC, loginov-rocks commented on webpack/webpack.config.common.js
> +    path: path.resolve('./public'),
This outputs to the `public` dir instead of `dist`. Prefer the last name.

2019-05-13 16:04 UTC, loginov-rocks commented on webpack/webpack.config.client.js
> +    !isDevMod && new CleanWebpackPlugin('./public',
Do you really want to clean `public` folder? It's a `dist`!

2019-05-13 16:05 UTC, loginov-rocks commented on webpack/webpack.config.common.js
> +        use: 'file-loader',
This is the place to locate options with publicPath

2019-05-13 16:05 UTC, loginov-rocks commented on server/app.js
> +  const serverRenderer = require('../public/js/serverRenderer').default;
And that should be changed to the `dist` as well.

2019-05-13 16:53 UTC, vm137 commented on package.json
>      "lint": "eslint --ext js,jsx src",
done

2019-05-14 06:06 UTC, loginov-rocks approved these changes

2019-05-14 06:12 UTC, merged